name: rtmag
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.4
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - tensorboard
  - torchmetrics
  - numpy
  - scipy
  - matplotlib
  - pyvista
  - tqdm
  - netcdf4
  - joblib
  - lightning